[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
allow_internal_expect_revert = true
bytecode_hash = "none"
cbor_metadata = false
dynamic_test_linking = true
ffi = true
fs_permissions = [{ access = "read", path = "out" }]
ignored_error_codes = [2394]
optimizer = true
optimizer_runs = 44444444
verbosity = 2
via_ir = true

additional_compiler_profiles = [
	{ name = "test", optimizer_runs = 1 }
]

compilation_restrictions = [
	{ paths = "test/**", optimizer_runs = 1 }
]

remappings = [
	"forge-std/=lib/forge-std/src/",
	"@openzeppelin/=lib/openzeppelin-contracts/contracts/",
	"permit2/=lib/permit2/src/"
]

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
func_attrs_with_params_multiline = true
inline_attribute_style = "compact"
return_statement = "inline"

[lint]
lint_on_build = false

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chainId = 1 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
